#
# https://www.sylvaindurand.org/making-jekyll-multilingual/
#
title: 
 en: In Da Chain Foundation
email: m@idc.foundation
name: In Da Chain Foundation
vision: 
 en: >
  The Blockchain Science group
baseurl: ""
url: "http://idc.foundation"
github: indachain
markdown: kramdown

collections:
 clients:
       output: false
 chains:
       output: false

gems:
  - jekyll-sitemap
